name: sensors_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.0
  sensors_plus: ^4.0.2
  proximity_sensor: ^1.3.1
  location: ^6.0.1
  flutter_compass: ^0.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/cadrant.png
    - assets/img/compass.png